modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/yggdyy/hexboard/issues"
license = "MIT"

[[mods]]
modId = "hexboard"
version = "${version}"
displayName = "HexBoard"
authors = "yggdyy_"
description = '''
A Hexcasting addon provides a board system to help writing hex.
'''
logoFile = "assets/hexboard/icon.png"

[[dependencies.hexboard]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexboard]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexboard]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexboard]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"
